Sleep time between retries
Elenpay/liquidator pull request #73
Opened 2024-03-27 13:23 UTC by markettes

This one implemets:
- Incremental sleep times between retries
- Max sleep time

2024-03-27 15:53 UTC, gcaracuel submitted a review, later dismissed
LGTM.
I won't override new flags as default values sounds like very good first pattern to check.

2024-04-17 15:15 UTC, Jossec101 requested changes
Sleep max can be removed, its not worth the code it adds for something trivial

2024-04-17 15:15 UTC, Jossec101 commented on liquidator.go
> +func performSwap(info ManageChannelLiquidityInfo, channel *lnrpc.Channel, swapAmount int64, rule nodeguard.LiquidityRule, span trace.Span, loopdCtx context.Context, retryCounter int, swapAmountTarget
if `sleepBetweenRetries` is a global, why send it over as a function param?

2024-04-17 15:15 UTC, Jossec101 commented on README.md
> +- SLEEPMAX (optional) : Maximum time to sleep between retries (default: 60s)
I think this is not useful, I would reduce code and actually control this via config rather making code more complex.

2024-06-20 08:30 UTC, gcaracuel commented
I guess this PR has fall behind some others and have not much sense now

2024-06-20 14:55 UTC, markettes commented
> I guess this PR has fall behind some others and have not much sense now

Test, I guess so

2024-06-24 11:34 UTC, Jossec101 commented
Let's close it

2024-06-24 11:34 UTC, closed without merging